apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sudoku-ingress
  namespace: sudoku
  annotations:
    # NGINX specific annotations for WebSocket support
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sudoku-app-service
                port:
                  number: 80